[Service]
EnvironmentFile=-/etc/sysconfig/aws-appconfig-agent
Environment=HTTP_HOST=localhost
Environment=HTTP_PORT=2772
Environment=LOG_LEVEL=warn
Environment=LOG_PATH=/var/log/aws/appconfig-agent.log
Environment=POLL_INTERVAL=45s
