#!/bin/bash
# Pulls the proxy runtime policy from the local AWS AppConfig Agent endpoint and
# renders three files that must change together:
#   * /etc/nginx/conf.d/sni_allowlist.conf
#   * /etc/nginx/conf.d/proxy_resolver.conf
#   * /etc/nginx/lua/proxy_runtime_policy.lua
#
# If AppConfig is temporarily unavailable, the script keeps the last known good
# rendered policy. If no AppConfig policy has ever been rendered on this
# instance, the sync fails so nginx does not start with stale bootstrap config.
set -euo pipefail

CONFIG_FILE=/etc/sysconfig/proxy-runtime-sync
ALLOWLIST_FILE=/etc/nginx/conf.d/sni_allowlist.conf
RESOLVER_FILE=/etc/nginx/conf.d/proxy_resolver.conf
LUA_POLICY_FILE=/etc/nginx/lua/proxy_runtime_policy.lua
RUNTIME_DIR=/var/lib/aws-firewall-proxy
CURRENT_POLICY_JSON="${RUNTIME_DIR}/current-policy.json"
LOG_FILE=/var/log/aws-firewall-proxy/runtime-sync.log
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

mkdir -p "$RUNTIME_DIR" "$(dirname "$LOG_FILE")"
exec >>"$LOG_FILE" 2>&1

log() {
    printf '%s proxy-runtime-sync: %s\n' "$(date -Iseconds)" "$1"
}

abort() {
    log "$1"
    exit 1
}

if [[ ! -r "$CONFIG_FILE" ]]; then
    abort "$CONFIG_FILE missing - cannot load runtime policy coordinates"
fi

# shellcheck disable=SC1090
source "$CONFIG_FILE"

: "${APPCONFIG_APPLICATION:?APPCONFIG_APPLICATION not set in $CONFIG_FILE}"
: "${APPCONFIG_ENVIRONMENT:?APPCONFIG_ENVIRONMENT not set in $CONFIG_FILE}"
: "${APPCONFIG_CONFIGURATION_PROFILE:?APPCONFIG_CONFIGURATION_PROFILE not set in $CONFIG_FILE}"

APPCONFIG_AGENT_HOST="${APPCONFIG_AGENT_HOST:-localhost}"
APPCONFIG_AGENT_PORT="${APPCONFIG_AGENT_PORT:-2772}"
APPCONFIG_URL="http://${APPCONFIG_AGENT_HOST}:${APPCONFIG_AGENT_PORT}/applications/${APPCONFIG_APPLICATION}/environments/${APPCONFIG_ENVIRONMENT}/configurations/${APPCONFIG_CONFIGURATION_PROFILE}"

render_allowlist_from_json() {
    local json_file="$1"
    local output_file="$2"

    {
        echo "# Auto-generated by refresh-proxy-runtime-policy.sh. Do not edit by hand."
        echo "# Source: AWS AppConfig ${APPCONFIG_APPLICATION}/${APPCONFIG_ENVIRONMENT}/${APPCONFIG_CONFIGURATION_PROFILE}"
        echo "map \$client_sni \$sni_allowed {"
        echo "    hostnames;"
        echo "    default 0;"
        jq -r '.allowed_snis[]? | select(type == "string" and length > 0) | "    .\(.) 1;"' "$json_file"
        echo "}"
    } > "$output_file"
}

render_resolver_from_json() {
    local json_file="$1"
    local output_file="$2"
    local resolvers

    resolvers=$(jq -r '.dns.resolvers | join(" ")' "$json_file")
    {
        echo "# Auto-generated by refresh-proxy-runtime-policy.sh. Do not edit by hand."
        echo "resolver ${resolvers} valid=10s ipv6=off;"
        echo "resolver_timeout 5s;"
    } > "$output_file"
}

render_runtime_policy_lua() {
    local json_file="$1"
    local output_file="$2"

    {
        echo "-- Auto-generated by refresh-proxy-runtime-policy.sh. Do not edit by hand."
        echo "return {"
        echo "    dns = {"
        echo "        resolvers = {"
        jq -r '.dns.resolvers[] | @json | "            " + . + ","' "$json_file"
        echo "        },"
        printf '        queries_per_sni = %s,\n' "$(jq -r '.dns.queries_per_sni' "$json_file")"
        echo "    },"
        echo "    enforcement = {"
        printf '        mode = %s,\n' "$(jq -r '.enforcement.mode | @json' "$json_file")"
        echo "    },"
        echo "}"
    } > "$output_file"
}

validate_policy_json() {
    local json_file="$1"

    jq -e '
        type == "object" and
        (.allowed_snis | type == "array" and all(.[]?; type == "string" and length > 0)) and
        (.dns | type == "object") and
        (.dns.resolvers | type == "array" and length >= 1 and all(.[]; type == "string" and length > 0)) and
        (.dns.queries_per_sni | type == "number" and floor == . and . >= 1 and . <= 16) and
        (.enforcement | type == "object") and
        (.enforcement.mode == "strict" or .enforcement.mode == "audit")
    ' "$json_file" >/dev/null
}

apply_rendered_files() {
    local allowlist_src="$1"
    local resolver_src="$2"
    local policy_src="$3"
    local policy_json_src="${4:-}"
    local backups_dir="${TMP_DIR}/backups"
    mkdir -p "$backups_dir"

    cp "$ALLOWLIST_FILE" "${backups_dir}/sni_allowlist.conf" 2>/dev/null || true
    cp "$RESOLVER_FILE" "${backups_dir}/proxy_resolver.conf" 2>/dev/null || true
    cp "$LUA_POLICY_FILE" "${backups_dir}/proxy_runtime_policy.lua" 2>/dev/null || true
    cp "$CURRENT_POLICY_JSON" "${backups_dir}/current-policy.json" 2>/dev/null || true

    install -m 0644 "$allowlist_src" "$ALLOWLIST_FILE"
    install -m 0644 "$resolver_src" "$RESOLVER_FILE"
    install -m 0644 "$policy_src" "$LUA_POLICY_FILE"
    if [[ -n "$policy_json_src" ]]; then
        install -m 0644 "$policy_json_src" "$CURRENT_POLICY_JSON"
    fi

    if ! nginx -t 2>/var/log/nginx/refresh-proxy-runtime-policy.err; then
        log "nginx -t failed, reverting generated policy files"
        [[ -f "${backups_dir}/sni_allowlist.conf" ]] && install -m 0644 "${backups_dir}/sni_allowlist.conf" "$ALLOWLIST_FILE"
        [[ -f "${backups_dir}/proxy_resolver.conf" ]] && install -m 0644 "${backups_dir}/proxy_resolver.conf" "$RESOLVER_FILE"
        [[ -f "${backups_dir}/proxy_runtime_policy.lua" ]] && install -m 0644 "${backups_dir}/proxy_runtime_policy.lua" "$LUA_POLICY_FILE"
        if [[ -f "${backups_dir}/current-policy.json" ]]; then
            install -m 0644 "${backups_dir}/current-policy.json" "$CURRENT_POLICY_JSON"
        else
            rm -f "$CURRENT_POLICY_JSON"
        fi
        exit 1
    fi

    if systemctl is-active --quiet nginx; then
        nginx -s reload
        log "reloaded nginx after runtime policy change"
    else
        log "rendered runtime policy before nginx startup"
    fi
}

APP_CONFIG_JSON="${TMP_DIR}/appconfig-policy.json"
ALLOWLIST_TMP="${TMP_DIR}/sni_allowlist.conf"
RESOLVER_TMP="${TMP_DIR}/proxy_resolver.conf"
LUA_POLICY_TMP="${TMP_DIR}/proxy_runtime_policy.lua"

if curl -fsS --max-time 10 "$APPCONFIG_URL" > "$APP_CONFIG_JSON"; then
    validate_policy_json "$APP_CONFIG_JSON"

    if [[ -f "$CURRENT_POLICY_JSON" ]] && cmp -s "$APP_CONFIG_JSON" "$CURRENT_POLICY_JSON"; then
        log "AppConfig policy unchanged"
        exit 0
    fi

    render_allowlist_from_json "$APP_CONFIG_JSON" "$ALLOWLIST_TMP"
    render_resolver_from_json "$APP_CONFIG_JSON" "$RESOLVER_TMP"
    render_runtime_policy_lua "$APP_CONFIG_JSON" "$LUA_POLICY_TMP"
    apply_rendered_files "$ALLOWLIST_TMP" "$RESOLVER_TMP" "$LUA_POLICY_TMP" "$APP_CONFIG_JSON"
    log "applied AppConfig runtime policy"
    exit 0
fi

if [[ -f "$CURRENT_POLICY_JSON" ]]; then
    log "AppConfig fetch failed; keeping last known good rendered policy"
    exit 0
fi

abort "failed to fetch AppConfig policy and no cached policy was available"
