#!/bin/bash
# Pulls the nginx SNI allowlist from SSM Parameter Store and renders it into
# /etc/nginx/conf.d/sni_allowlist.conf. Reloads nginx only if the rendered
# file changed. Idempotent - safe to run from a timer.
#
# Parameter name is read from /etc/sysconfig/nginx-sni-allowlist (written by
# user_data, since the parameter name depends on the environment prefix).
set -euo pipefail

CONFIG_FILE=/etc/sysconfig/nginx-sni-allowlist
SNIPPET=/etc/nginx/conf.d/sni_allowlist.conf
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

if [[ ! -r "$CONFIG_FILE" ]]; then
    echo "refresh-sni-allowlist: $CONFIG_FILE missing - skipping" >&2
    exit 0
fi

# shellcheck disable=SC1090
source "$CONFIG_FILE"
: "${SSM_PARAMETER_NAME:?SSM_PARAMETER_NAME not set in $CONFIG_FILE}"
: "${AWS_REGION:?AWS_REGION not set in $CONFIG_FILE}"

VALUE=$(aws ssm get-parameter \
    --region "$AWS_REGION" \
    --name "$SSM_PARAMETER_NAME" \
    --query 'Parameter.Value' \
    --output text)

{
    echo "# Auto-generated by refresh-sni-allowlist.sh. Do not edit by hand."
    echo "# Source: SSM parameter $SSM_PARAMETER_NAME"
    echo "map \$spike_sni \$sni_allowed {"
    echo "    hostnames;"
    echo "    default 0;"
    # The SSM StringList comes back as comma-separated. Leading-dot form lets
    # nginx's `hostnames` map mode match both the apex and subdomains.
    IFS=',' read -ra FQDNS <<< "$VALUE"
    for fqdn in "${FQDNS[@]}"; do
        fqdn=$(echo "$fqdn" | xargs)
        [[ -z "$fqdn" ]] && continue
        printf '    .%s 1;\n' "$fqdn"
    done
    echo "}"
} > "$TMP"

if cmp -s "$TMP" "$SNIPPET"; then
    exit 0
fi

cp "$SNIPPET" "${SNIPPET}.bak"
install -m 0644 "$TMP" "$SNIPPET"
if ! nginx -t 2>/var/log/nginx/refresh-sni-allowlist.err; then
    echo "refresh-sni-allowlist: nginx -t failed, reverting" >&2
    mv "${SNIPPET}.bak" "$SNIPPET"
    exit 1
fi
rm -f "${SNIPPET}.bak"

if systemctl is-active --quiet nginx; then
    nginx -s reload
fi
